(() => {
  'use strict';
  const ITEMS=Object.freeze([
    {title:'Novo indicado',section:'Principal',url:'/',keywords:'novo indicado busca exaustiva jogo indicação'},
    {title:'Análise',section:'Principal',url:'/?page=analysis',keywords:'analise filtros métricas'},
    {title:'Geradores',section:'Principal',url:'/?page=generator',keywords:'gerador jogos'},
    {title:'Matriz 51',section:'Principal',url:'/?page=matrix',keywords:'51 filtros matriz'},
    {title:'Estatísticas',section:'Principal',url:'/?page=statistics',keywords:'estatisticas frequência'},
    {title:'Backtest',section:'Validação',url:'/?page=backtest',keywords:'backtest walk forward'},
    {title:'Laboratório',section:'Validação',url:'/?page=lab',keywords:'laboratorio trocas fixas'},
    {title:'Tabela Vertical',section:'Validação',url:'/?page=vertical',keywords:'vertical 1'},
    {title:'Vertical 2',section:'Validação',url:'/?page=vertical2',keywords:'vertical 2'},
    {title:'Duplas / Trincas',section:'Análises',url:'/?page=pairs',keywords:'pares duplas trincas'},
    {title:'Posições D1–D15',section:'Análises',url:'/?page=positions',keywords:'posições d1 d15'},
    {title:'Manual de uso',section:'Ajuda',url:'/manual.html',keywords:'manual ajuda instruções'},
    {title:'Raio-X do Concurso',section:'Inteligência',url:'/inteligencia.html#raiox',keywords:'raio x concurso padrões'},
    {title:'DNA Lotofácil',section:'Inteligência',url:'/inteligencia.html#dna',keywords:'dna atraso frequência ciclo'},
    {title:'Comportamento das 25 dezenas',section:'Inteligência',url:'/inteligencia.html#behavior',keywords:'25 dezenas comportamento f10 f20 f50 f100 tendência'},
    {title:'Final do concurso 0–9',section:'Inteligência',url:'/inteligencia.html#finals',keywords:'final concurso 0 9'},
    {title:'Lotofácil da Independência',section:'Inteligência',url:'/inteligencia.html#independencia',keywords:'independência especial'},
    {title:'Fechamentos+',section:'Inteligência',url:'/inteligencia.html#closures',keywords:'fechamento cobertura'},
    {title:'Portfólio Inteligente',section:'Inteligência',url:'/inteligencia.html#portfolio',keywords:'portfolio 5 10 20 50 diversidade'},
    {title:'Probabilidades',section:'Inteligência',url:'/inteligencia.html#probability',keywords:'probabilidade matemática'},
    {title:'Filtros personalizados',section:'Operações',url:'/operacoes.html#filters',keywords:'filtros personalizados perfil'},
    {title:'Grupos Premiados / Virgens',section:'Operações',url:'/operacoes.html#groups',keywords:'grupos premiados virgens'},
    {title:'TUP',section:'Operações',url:'/operacoes.html#tup',keywords:'tabela universal prêmios grupos'},
    {title:'Matriz certificada',section:'Operações',url:'/operacoes.html#matrix',keywords:'matriz garantia certificada'},
    {title:'Arquivos de jogos',section:'Operações',url:'/operacoes.html#files',keywords:'importar exportar excel csv txt json'},
    {title:'Inventário',section:'Operações',url:'/operacoes.html#inventory',keywords:'inventário frequências arquivo'},
    {title:'Conferidor+',section:'Operações',url:'/operacoes.html#checker',keywords:'conferir premiados'},
    {title:'União / Cartesiana',section:'Operações',url:'/operacoes.html#combine',keywords:'união cartesiana arquivos'},
    {title:'Geração em lote',section:'Operações',url:'/operacoes.html#batch',keywords:'lote gerar jogos'},
    {title:'Impressão A4',section:'Operações',url:'/operacoes.html#print',keywords:'imprimir a4 jogos'},
    {title:'Explorador Histórico',section:'Histórico Avançado',url:'/historico-avancado.html#explorer',keywords:'combinações contém não contém histórico'},
    {title:'Ciclos Avançados',section:'Histórico Avançado',url:'/historico-avancado.html#cycles',keywords:'ciclos pares impares primos fibonacci linhas colunas'},
    {title:'Sequências / Saltos',section:'Histórico Avançado',url:'/historico-avancado.html#runs',keywords:'sequências saltos'},
    {title:'Matriz 25×25',section:'Histórico Avançado',url:'/historico-avancado.html#siblings',keywords:'acompanhantes irmãos pares 25x25'},
    {title:'Binário Histórico',section:'Histórico Avançado',url:'/historico-avancado.html#binary',keywords:'binário 0 1'},
    {title:'Grupos 21 dezenas',section:'Histórico Avançado',url:'/historico-avancado.html#g21',keywords:'21 dezenas grupo'},
    {title:'Ausências',section:'Histórico Avançado',url:'/historico-avancado.html#absent',keywords:'ausentes falhas'},
    {title:'Padrões Históricos',section:'Histórico Avançado',url:'/historico-avancado.html#patterns',keywords:'padrões histórico distribuição'},
    {title:'Pareto / Pesos',section:'Histórico Avançado',url:'/historico-avancado.html#pareto',keywords:'pareto pesos ranking'},
    {title:'Estatísticas+',section:'Estatísticas+',url:'/estatisticas-plus.html',keywords:'diagnóstico descartes filtros observado esperado faixas típicas saltos +2 concentração pareto heatmap presets'},
    {title:'Descartes por Filtro',section:'Estatísticas+',url:'/estatisticas-plus.html#discard',keywords:'busca real filtros bloqueadores estrangulamento geração'},
    {title:'Observado × Esperado',section:'Estatísticas+',url:'/estatisticas-plus.html#expected',keywords:'esperado matemático 60% frequência desvio'},
    {title:'Faixas Típicas',section:'Estatísticas+',url:'/estatisticas-plus.html#ranges',keywords:'percentil p10 p25 mediana p75 p90 calibração'},
    {title:'Saltos +2',section:'Estatísticas+',url:'/estatisticas-plus.html#jump2',keywords:'sequência salto dois progressão'},
    {title:'Concentração Linha/Coluna',section:'Estatísticas+',url:'/estatisticas-plus.html#concentration',keywords:'máximo linha coluna distribuição'},
    {title:'Pareto Top 5',section:'Estatísticas+',url:'/estatisticas-plus.html#pareto',keywords:'top 5 participação 20%'},
    {title:'Heatmap do Esperado',section:'Estatísticas+',url:'/estatisticas-plus.html#heatmap',keywords:'mapa calor esperado acima abaixo'},
    {title:'Presets de Pesos',section:'Estatísticas+',url:'/estatisticas-plus.html#presets',keywords:'equilibrado quentes frias pesos'},
    {title:'Rastreador de Indicações',section:'Evoluções',url:'/evolucoes.html#tracker',keywords:'rastreador novo indicado histórico pontuação'},
    {title:'Movimentação das Dezenas',section:'Evoluções',url:'/evolucoes.html#movement',keywords:'movimentação ranking tendência emojis'},
    {title:'Figuras / Padrões Populares',section:'Evoluções',url:'/evolucoes.html#figures',keywords:'figuras padrões cruz x h estrela'},
    {title:'Super Falhas',section:'Evoluções',url:'/evolucoes.html#failures',keywords:'super falhas ausências mapa'},
    {title:'Editor de Regiões',section:'Evoluções',url:'/evolucoes.html#regions',keywords:'regiões volante personalizada'},
    {title:'Matrizes Estruturais 9D/10D',section:'Evoluções',url:'/evolucoes.html#structural',keywords:'linha linha coluna coluna 9d 10d matrizes'},
    {title:'Gerador 21D',section:'Evoluções',url:'/evolucoes.html#g21gen',keywords:'gerador 21 dezenas linha coluna'},
    {title:'Busca Global',section:'Evoluções',url:'/evolucoes.html#search',keywords:'busca global pesquisar módulos'}
  ]);
  function norm(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()}
  function search(q){const n=norm(q).trim();if(!n)return ITEMS.slice(0,20);const toks=n.split(/\s+/);return ITEMS.map(x=>{const h=norm(x.title+' '+x.section+' '+x.keywords);let score=0;for(const t of toks){if(norm(x.title).includes(t))score+=5;if(norm(x.section).includes(t))score+=2;if(h.includes(t))score+=1}return{x,score}}).filter(z=>z.score>0).sort((a,b)=>b.score-a.score||a.x.title.localeCompare(b.x.title)).map(z=>z.x)}
  window.LFGlobalSearch=Object.freeze({ITEMS,search});
})();