(()=>{'use strict';
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const pageTitle=name=>{const b=document.querySelector('.nav-item[data-page="'+name+'"] b');return b?.textContent?.trim()||name;};
  function fallbackPage(name){if(window.__LF_APP_READY)return;const panel=$('.page[data-page-panel="'+name+'"]');if(!panel)return;$$('.page').forEach(p=>p.classList.toggle('active',p===panel));$$('.nav-item[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===name));const t=$('#page-title');if(t)t.textContent=pageTitle(name);$('#sidebar')?.classList.remove('open');try{history.replaceState(null,'',name==='decision'?location.pathname:location.pathname+'?page='+encodeURIComponent(name));}catch{}}
  function toggleGroup(btn){if(window.__LF_APP_READY)return;const g=btn.closest('.nav-group');if(!g)return;const open=!g.classList.contains('open');g.classList.toggle('open',open);btn.setAttribute('aria-expanded',String(open));}
  function filterNav(input){if(window.__LF_APP_READY)return;const q=String(input.value||'').trim().toLowerCase(),groups=$$('.nav-group');let visible=0;for(const g of groups){let n=0;g.querySelectorAll('.nav-item').forEach(item=>{const hit=!q||item.textContent.toLowerCase().includes(q);item.hidden=!hit;if(hit){n++;visible++;}});g.hidden=!!q&&!n;if(q&&n)g.classList.add('open');}$$('.nav-shortcuts .nav-item').forEach(item=>{const hit=!q||item.textContent.toLowerCase().includes(q);item.hidden=!hit;if(hit)visible++;});const empty=$('#nav-empty');if(empty)empty.hidden=visible>0;const box=$('#nav-global-results'),rs=q&&window.LFGlobalSearch?window.LFGlobalSearch.search(q).slice(0,8):[];if(box){box.hidden=!rs.length;box.innerHTML=rs.map(x=>'<a href="'+x.url+'"><b>'+x.title+'</b><small>'+x.section+'</small></a>').join('');}}
  document.addEventListener('click',e=>{if(window.__LF_APP_READY)return;const menu=e.target.closest?.('#menu-button');if(menu){$('#sidebar')?.classList.toggle('open');return;}const group=e.target.closest?.('.nav-group-toggle');if(group){toggleGroup(group);return;}const nav=e.target.closest?.('.nav-item[data-page]');if(nav){e.preventDefault();fallbackPage(nav.dataset.page);}});
  document.addEventListener('input',e=>{if(e.target?.id==='nav-search')filterNav(e.target);});
  window.addEventListener('lf:app-failed',()=>{document.documentElement.dataset.lfFallback='1';const s=$('#data-status');if(s)s.textContent='Modo de contingência ativo';});
})();