(()=>{'use strict';
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const pageTitle=name=>{const b=document.querySelector('.nav-item[data-page="'+name+'"] b');return b?.textContent?.trim()||name;};
  function fallbackPage(name){if(window.__LF_APP_READY)return;const panel=$('.page[data-page-panel="'+name+'"]');if(!panel)return;$$('.page').forEach(p=>p.classList.toggle('active',p===panel));$$('.nav-item[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===name));const t=$('#page-title');if(t)t.textContent=pageTitle(name);$('#sidebar')?.classList.remove('open');try{history.replaceState(null,'',name==='decision'?location.pathname:location.pathname+'?page='+encodeURIComponent(name));}catch{}}
  function toggleGroup(btn){if(window.__LF_APP_READY)return;const g=btn.closest('.nav-group');if(!g)return;const open=!g.classList.contains('open');g.classList.toggle('open',open);btn.setAttribute('aria-expanded',String(open));}
  function filterNav(input){if(window.__LF_APP_READY)return;const q=String(input.value||'').trim(),active=!!q;document.body.classList.toggle('nav-searching',active);const clear=$('#nav-search-clear');if(clear)clear.hidden=!active;const empty=$('#nav-empty'),box=$('#nav-global-results'),rs=active&&window.LFGlobalSearch?window.LFGlobalSearch.search(q).slice(0,12):[];if(box){box.hidden=!rs.length;box.innerHTML=rs.map(x=>'<a href="'+x.url+'"><b>'+x.title+'</b><em>ABRIR</em><small>'+x.section+'</small></a>').join('');}if(empty)empty.hidden=rs.length>0;}
  document.addEventListener('click',e=>{if(window.__LF_APP_READY)return;const menu=e.target.closest?.('#menu-button');if(menu){$('#sidebar')?.classList.toggle('open');return;}if(e.target.closest?.('#sidebar-close')){$('#sidebar')?.classList.remove('open');return;}if(e.target.closest?.('#nav-search-clear')){const input=$('#nav-search');if(input){input.value='';filterNav(input);input.focus();}return;}const group=e.target.closest?.('.nav-group-toggle');if(group){const g=group.closest('.nav-group'),next=!g.classList.contains('open');$('.nav-group').forEach(x=>{if(x!==g)x.classList.remove('open');});g.classList.toggle('open',next);group.setAttribute('aria-expanded',String(next));return;}const nav=e.target.closest?.('.nav-item[data-page]');if(nav){e.preventDefault();fallbackPage(nav.dataset.page);}});
  document.addEventListener('input',e=>{if(e.target?.id==='nav-search')filterNav(e.target);});
  window.addEventListener('lf:app-failed',()=>{document.documentElement.dataset.lfFallback='1';const s=$('#data-status');if(s)s.textContent='Modo de contingência ativo';});
})();