const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const base=require('../data/lotofacil-base.json');
const sandbox={window:{}};
vm.runInNewContext(fs.readFileSync(require.resolve('../matrix-51.js'),'utf8'),sandbox);
const M=sandbox.window.LFMatrix51;
const history=base.history;
const appSource=fs.readFileSync(require.resolve('../app.js'),'utf8');
const workerSource=fs.readFileSync(require.resolve('../analysis-worker.js'),'utf8');
const matrixSource=fs.readFileSync(require.resolve('../matrix-51.js'),'utf8');
const indexSource=fs.readFileSync(require.resolve('../index.html'),'utf8');
const primaryNavStart=indexSource.indexOf('<div class="nav-primary-list">');
const primaryNavEnd=indexSource.indexOf('</div>',primaryNavStart);
const primaryNav=indexSource.slice(primaryNavStart,primaryNavEnd);
const proPos=primaryNav.indexOf('id="nav-pro-profile"');
const v1Pos=primaryNav.indexOf('data-page="vertical"');
const v2Pos=primaryNav.indexOf('data-page="vertical2"');
const v3Pos=primaryNav.indexOf('data-page="vertical3"');
const analysisPos=primaryNav.indexOf('data-page="analysis"');
assert.ok(proPos>=0&&v1Pos>proPos&&v2Pos>v1Pos&&v3Pos>v2Pos&&analysisPos>v3Pos,'Menu lateral deve ordenar Perfil PRO → Vertical 1 → Vertical 2 → Vertical 3 → Analisar jogo');
assert.equal((indexSource.match(/data-page="vertical"/g)||[]).length,1,'Vertical 1 não deve ficar duplicada no menu lateral');
assert.equal((indexSource.match(/data-page="vertical2"/g)||[]).length,1,'Vertical 2 não deve ficar duplicada no menu lateral');
assert.equal((indexSource.match(/data-page="vertical3"/g)||[]).length,1,'Vertical 3 não deve ficar duplicada no menu lateral');
assert.ok(appSource.includes('function restartDecisionExhaustiveAfterMiss'),'Busca exaustiva deve possuir reinício automático quando não formar 15 dezenas');
assert.ok(appSource.includes('const maxAttempts=5'),'Busca exaustiva deve limitar a 5 tentativas no total');
assert.ok(appSource.includes('currentAttempt>=maxAttempts'),'Após a quinta tentativa deve abrir o desbloqueio');
assert.ok(appSource.includes('M.FILTERS.map'),'Painel de desbloqueio deve listar os 51 filtros');
assert.ok(appSource.includes('F29 é permanente'),'Painel deve informar que F29 nunca pode ser liberado');
assert.ok(appSource.includes("permanent||!blocked?'disabled':''"),'F29 e filtros já não bloqueadores devem ficar desabilitados para desbloqueio');
assert.ok(appSource.includes('id!==29'),'Aplicação do desbloqueio deve excluir F29');
assert.ok(appSource.includes("state.filterPolicies[29]='block'"),'F29 deve permanecer BLOQUEADO no estado do app');
assert.ok(workerSource.includes("Number(f.id)===29?'block'"),'Worker deve manter F29 como bloqueio absoluto');
assert.ok(matrixSource.includes("Number(f.id)===29?'block'"),'Matriz 51 deve manter F29 como bloqueio absoluto');
assert.ok(appSource.includes("status==='running'?`${tested.toLocaleString('pt-BR')} / ${total?total.toLocaleString('pt-BR'):'—'}`"),'Total a avaliar deve começar em zero e avançar como avaliado/universo');
assert.ok((appSource.match(/restartDecisionExhaustiveAfterMiss\(d\.diagnostics\|\|null\)/g)||[]).length>=2,'Os dois caminhos sem jogo válido devem reiniciar a busca');
assert.equal(history.length,base.baseValidation.loadedCount);
assert.equal(base.latest.concurso,history.at(-1).concurso);
for(let i=0;i<history.length;i++){
  const row=history[i];
  assert.equal(row.concurso,i+1);
  assert.equal(row.dezenas.length,15);
  assert.equal(new Set(row.dezenas).size,15);
  assert.ok(row.dezenas.every(n=>Number.isInteger(n)&&n>=1&&n<=25));
}
const ctx=M.buildContext(history),last=history.at(-1).dezenas;
const inspect=game=>M.inspect(game,ctx);
const filter=(report,id)=>report.filters.find(f=>f.id===id);
const exact=inspect(last);
assert.equal(filter(exact,29).passed,false,'F29 deve bloquear concurso já sorteado');
assert.equal(filter(exact,37).passed,false,'F37 deve bloquear 15/15 histórico');
assert.equal(filter(exact,36).passed,false,'F36 deve bloquear 3+ anomalias simultâneas neste caso');
assert.equal(exact.lineRepeat.blocked,true);
assert.equal(exact.columnRepeat.blocked,true);
const replacement=Array.from({length:25},(_,i)=>i+1).find(n=>!last.includes(n));
const near=[...last.slice(0,14),replacement].sort((a,b)=>a-b);
assert.equal(filter(inspect(near),37).passed,false,'F37 deve bloquear 14/15 histórico');
const fewColors=[1,11,21,2,12,22,3,13,23,4,14,24,5,15,25];
assert.equal(inspect(fewColors).colorRule.blocked,true,'menos de 8 cores deve bloquear');
for(const id of [28,29,36,37])assert.ok(filter(exact,id),'filtro obrigatório F'+id+' ausente');
assert.equal(M.AUDIT_BASE_THROUGH,history.at(-1).concurso);
console.log(`Auditoria local: ${history.length} concursos contínuos; F29, F36, F37, cores e Linha/Coluna verificados.`);
